### ISSUE TITLE
./yii rbac/init fail: Table 'yii2basic.auth_rule' doesn't exist

### ISSUE THREAD

**Issue by JumpingYang001** [gittestapi/gittest#18]
```
[root@host basic]# ./yii rbac/init
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii2basic.auth_rule' doesn't exist
The SQL being executed was: INSERT INTO `auth_rule` (`name`, `data`, `created_at`, `updated_at`) VALUES ('isRepoAuthor', 'O:23:\"app\\rbac\\RepoAuthorRule\":3:{s:4:\"name\";s:12:\"isRepoAuthor\";s:9:\"createdAt\";i:1506754915;s:9:\"updatedAt\";i:1506754915;}', 1506754915, 1506754915)'

in /var/www/html/gittest/basic/vendor/yiisoft/yii2/db/Schema.php:636

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yii2basic.auth_rule' doesn't exist
)

Stack trace:
#0 /var/www/html/gittest/basic/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `au...')
#1 /var/www/html/gittest/basic/vendor/yiisoft/yii2/rbac/DbManager.php(359): yii\db\Command->execute()
#2 /var/www/html/gittest/basic/vendor/yiisoft/yii2/rbac/BaseManager.php(127): yii\rbac\DbManager->addRule(Object(app\rbac\RepoAuthorRule))
#3 /var/www/html/gittest/basic/commands/RbacController.php(15): yii\rbac\BaseManager->add(Object(app\rbac\RepoAuthorRule))
#4 [internal function]: app\commands\RbacController->actionInit()
#5 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('init', Array)
#8 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('init', Array)
#9 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('rbac/init', Array)
#10 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('rbac/init', Array)
#11 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /var/www/html/gittest/basic/yii(20): yii\base\Application->run()
#13 {main}

```

**Comment by JumpingYang001** [comment]
auth_rule 这个表貌似没找到额。

**Comment by yangzhenping** [comment]
Fixed in https://github.com/gittestapi/gittest/commit/6c59d483fde2f222dd782ad4387eedf7b950bf29
