### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii2basic.joinrepo' doesn't exist

### ISSUE THREAD

**Issue by JumpingYang001** [gittestapi/gittest#19]
```
[root@host basic]# ./yii migrate --migrationPath=migrations
Yii Migration Tool (based on Yii v2.0.11.2)

Creating migration history table "migration"...Done.
Total 3 new migrations to be applied:
        m170921_062604_add_role_column_to_joinrepo_table
        m170921_093425_add_foreignKey_to_joinrepo_table
        m170925_075054_create_request_table

Apply the above migrations? (yes|no) [no]:yes
*** applying m170921_062604_add_role_column_to_joinrepo_table
    > add column role string(1) to table joinrepo ...Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii2basic.joinrepo' doesn't exist
The SQL being executed was: ALTER TABLE `joinrepo` ADD `role` varchar(1)'

in /var/www/html/gittest/basic/vendor/yiisoft/yii2/db/Schema.php:636

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yii2basic.joinrepo' doesn't exist
)

Stack trace:
#0 /var/www/html/gittest/basic/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `jo...')
#1 /var/www/html/gittest/basic/vendor/yiisoft/yii2/db/Migration.php(332): yii\db\Command->execute()
#2 /var/www/html/gittest/basic/migrations/m170921_062604_add_role_column_to_joinrepo_table.php(15): yii\db\Migration->addColumn('joinrepo', 'role', Object(yii\db\mysql\ColumnSchemaBuilder))
#3 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(654): m170921_062604_add_role_column_to_joinrepo_table->up()
#4 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('m170921_062604_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#9 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#10 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#11 /var/www/html/gittest/basic/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#12 /var/www/html/gittest/basic/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /var/www/html/gittest/basic/yii(20): yii\base\Application->run()
#14 {main}

```

**Comment by JumpingYang001** [comment]
这是大小写问题，在Linux上是区分大小写的。
https://github.com/gittestapi/gittest/blob/master/mysql.txt 这里用的是大写。
https://github.com/gittestapi/gittest/blob/master/basic/migrations/m170921_062604_add_role_column_to_joinrepo_table.php 代码里用的是小写。

**Comment by yangzhenping** [comment]
Fixed.
